#!/usr/bin/env bash

ABI="-mabi=purecap-benchmark"
WARN="-Wno-cheri-inefficient -Wno-cheri-capability-misuse -Wno-cheri-provenance"
HACK="-DC18N_NO_COPY_HACK"

# curl -s https://raw.githubusercontent.com/spdk-morello/spdk/c18n-benchmark/c18n-run | bash

if [ ! -f ./c18n-run ]
then
	exec 0</dev/tty
	sudo pkg64c install -qy git bash
	git clone https://github.com/spdk-morello/spdk .
	git checkout c18n-benchmark
	exec ./c18n-run
fi

# Install package dependencies

sudo pkg64cb install -qy e2fsprogs-libuuid cunit curl

[ -f fio/fio -a -d build ] || (
	sudo pkg64 install -qy meson ninja python llvm llvm-base py39-pip gdb-cheri \
		pkgconf openssl e2fsprogs-libuuid ncurses py39-pyelftools \
		autoconf automake libtool help2man doxygen mscgen graphviz
	sudo pkg64c install -qy bash git gmake
	pip install -q pyelftools
)

# Build

[ -d dpdk/config ] || git submodule update --init

[ -f fio/fio ] || (
	cd fio;
	./configure --disable-shm --extra-cflags="$ABI $WARN $HACK" \
		--extra-ldflags="-mabi=purecap-benchmark" && gmake -j4
)

[ -d build ] || (
	CFLAGS="$ABI $WARN $HACK" CXXFLAGS="$ABI $WARN $HACK" LDFLAGS="$ABI" \
		./configure --target-arch=morello --disable-tests --disable-unit-tests --disable-apps --with-fio=`pwd`/fio --with-shared
	gmake -j4
)

# Run ramdisk test

SPDK=`pwd`/build
DPDK=`pwd`/dpdk/build

echo 'Running with C18N disabled'
LD_64CB_LIBRARY_PATH=.:/usr/local64cb/lib:${SPDK}/lib:${SPDK}/fio:${DPDK}/lib \
	proccontrol -m cheric18n -s disable \
	./fio/fio ./examples/bdev/fio_plugin/example_config.fio 2>&1 | \
	egrep 'READ:|WRITE:|fail|FATAL| lat \(usec\):'

echo 'Running with C18N enabled'
LD_64CB_LIBRARY_PATH=.:/usr/local64cb/lib:${SPDK}/lib:${SPDK}/fio:${DPDK}/lib \
	proccontrol -m cheric18n -s enable ./fio/fio ./examples/bdev/fio_plugin/example_config.fio 2>&1 | \
	egrep 'READ:|WRITE:|fail|FATAL| lat \(usec\):'

