#!/usr/bin/env bash

ABI="-mabi=purecap-benchmark"
WARN="-Wno-cheri-inefficient -Wno-cheri-capability-misuse -Wno-cheri-provenance"
HACK="-DC18N_NO_COPY_HACK"

# curl -s https://raw.githubusercontent.com/spdk-morello/spdk/c18n-benchmark/c18n-run | bash

if [ ! -f ./c18n-run ]
then
	exec 0</dev/tty
	sudo pkg64c install -qy git bash
	git clone https://github.com/spdk-morello/spdk .
	git checkout c18n-benchmark
	exec ./c18n-run
fi

# Install package dependencies

sudo pkg64cb install -qy e2fsprogs-libuuid cunit curl

[ -f fio/fio -a -d build ] || (
	sudo pkg64 install -qy meson ninja python llvm llvm-base py39-pip gdb-cheri \
		pkgconf openssl e2fsprogs-libuuid ncurses py39-pyelftools \
		autoconf automake libtool help2man doxygen mscgen graphviz
	sudo pkg64c install -qy bash git gmake
	pip install -q pyelftools
)

# Build

[ -d dpdk/config ] || git submodule update --init

[ -f fio/fio ] || (
	cd fio;
	./configure --disable-shm --extra-cflags="$ABI $WARN $HACK" \
		--extra-ldflags="-mabi=purecap-benchmark" && gmake -j4
)

[ -d build ] || (
	CFLAGS="$ABI $WARN $HACK" CXXFLAGS="$ABI $WARN $HACK" LDFLAGS="$ABI" \
		./configure --target-arch=morello --disable-tests --disable-unit-tests --disable-apps --with-fio=`pwd`/fio --with-shared
	gmake -j4
)

# Run ramdisk tests

run_fio () {
(
	if [ "$1" = "1" ]
	then
		sed -e"s/^bs=.*/bs=512/" < ./examples/bdev/fio_plugin/example_config.fio > ./build/spdk.fio
		export C18N_NO_COPY_HACK=1
	else
		sed -e"s/^bs=.*/bs=$1/" < ./examples/bdev/fio_plugin/example_config.fio > ./build/spdk.fio
	fi

	export LD_64CB_LIBRARY_PATH=.:/usr/local64cb/lib:`pwd`/build/lib:`pwd`/build/fio:`pwd`/dpdk/build/lib

	proccontrol -m cheric18n -s disable ./fio/fio ./build/spdk.fio 2>&1 | \
		egrep 'read:|fail|FATAL' | sed -e"s/read/$1\t\t/"
	proccontrol -m cheric18n -s enable ./fio/fio ./build/spdk.fio 2>&1 | \
		egrep 'read:|fail|FATAL' | sed -e"s/read/$1 c18n\t/"

	rm -f ./build/spdk.fio
)
}

for i in 1 512 4k 8k 16k 32k 64k 128k 256k
do run_fio $i
done
